### ISSUE TITLE
Flowers do not drop

### ISSUE THREAD

**Issue by ringprod** [tumGER/FlowerPower#6]
When mining flowers in survival, the item does not drop.

**Comment by AnnsAnns** [comment]
Are you talking about the flowers themselves or the petals? The petals are crafted through this crafting recipe as seen in the ReadMe: 
![grafik](https://github.com/tumGER/FlowerPower/assets/25822956/cea92ac7-7409-4272-83db-ced85160ea55)

**Comment by ringprod** [comment]
The petals, when they are placed and you mine them, they just disappear and do not drop anything.

**Comment by AnnsAnns** [comment]
Oh yeah you're right, thank you for letting me know, it seems like this was a regression caused by internal changes that happened in one Minecraft Snapshot. I'll fix it in the next version.

**Comment by AnnsAnns** [comment]
Fixed in v1.1.0

**Comment by AnnsAnns** [comment]
https://modrinth.com/mod/flower-power/version/1.1.0
