### ISSUE TITLE
Petals don't inherit proper tags

### ISSUE THREAD

**Issue by DadoIrie** [tumGER/FlowerPower#7]
loving it and def a missing feature in minecraft
just one important detail is missing here - bees do pollinate the vanilla pink petals, but sadly not the flower power ones
could that be implemented?

EDIT: just tested it thorough: can't breed bees & can't be tempted with flower power petals and they go to any other flowers & vanilla petals to pollinate except flower power petals

**Comment by AnnsAnns** [comment]
Hey, thank you so much for using my mod, I'm glad that you're enjoying it. That's a good point, I'll investigate why this is happening but I already have a theory. I'll try to implement/fix this asap 😄

**Comment by AnnsAnns** [comment]
This has been fixed https://github.com/tumGER/FlowerPower/commit/78d65294dc2e09abfa4bc9bb971185e1f99ae0ee https://github.com/tumGER/FlowerPower/commit/6da0eddb4ae0b3de9a7f349ce91c4fc926e92b22. Will, most likely, be released today.

**Comment by AnnsAnns** [comment]
Fix has been released. https://modrinth.com/mod/flower-power/version/1.2.0
