### ISSUE TITLE
Support Forge

### ISSUE THREAD

**Issue by AnnsAnns** [tumGER/FlowerPower#8]
While I personally don't use Forge for modern Minecraft versions, it'd be neat to support it, esp. since most resources can be shared.

So far there has been a tiny bit of work done on the https://github.com/tumGER/FlowerPower/tree/gewerkschaft branch but this would still be a major undertaking. I might even create a minimal Forge version in v2.0 and then later merge all versions into a single one.

Also, I haven't touched Forge modding since like Minecraft version 1.7.x so we'll see how awful it actually is to maintain.

**Comment by AnnsAnns** [comment]
Given the current events I've decided to create the Forge version once NeoForged is stable and ready to go.

**Comment by Czompi** [comment]
Hi,

I wrote a comment on your related PR, but I thought, that I'll continue it here.

In the past few hours I've been fiddling with the multiloader port of your mod and I got it fully working in Fabric.
Forge works, but petals are not transparent. I'll look into that, I hope that I'd be done with it in the next few days.
Quilt will work, but the template-provided `quilt.mod.json` file is not in the current Quilt standard and it crashes (it will be fixed in my next commit).

**Comment by AnnsAnns** [comment]
Hey, I'm really happy to hear that. I'll look into this next week as I currently don't have access to a setup required to do. Thank you so much for your work though!Am 21.07.2023 22:24 schrieb Dávid Czompó ***@***.***>:
Hi,
I wrote a comment on your related PR, but I thought, that I'll continue it here.
In the past few hours I've been fiddling with the multiloader port of your mod and I got it fully working in Fabric.
Forge works, but petals are not transparent. I'll look into that, I hope that I'd be done with it in the next few days.
Quilt will work, but the template-provided quilt.mod.json file is not in the current Quilt standard and it crashes (it will be fixed in my next commit).

**Comment by Czompi** [comment]
Hi,

I finally had time to finish my PR.
Platform specific jar files will generate in `<platform>/build/libs/` folder.

**Comment by AnnsAnns** [comment]
Hey, just as a little update to not keep you in the dark. Thank you so much for the PR first of all. Right now I'm not too sure how to move forward with multi-platform support though. 

I might decide it when a new Minecraft version comes out but for now I'm quite split between Architectury or just making a seperate NeoForge version.
Quilt support actually isn't that important to me, mostly because I just found their entire community to be way too walled garden to want to properly maintain a quilt-specific version. Funfact, originally this entire mod was supposed to be a Quilt mod actually, till I had a small issue I wanted to ask a question about only to be greeted with an entire application process on a discord just to literally be able to read the dev support channel.

Either way, I'm not too certain with what approach I want to take for (Neo)Forge support right now.

**Comment by AnnsAnns** [comment]
It is also heavily depended on what the next Minecraft version is going to be, in the case that it possibly expends on the flowers or is hype enough to get my attention I'll probably once again commit more time to this mod.
